# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-15 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Code', models.CharField(max_length=10)),
                ('Credits', models.IntegerField()),
                ('Is_Core', models.BooleanField()),
                ('semester', models.IntegerField()),
                ('Instructor', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=15)),
                ('Email', models.CharField(max_length=100)),
            ],
        ),
    ]
