# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-16 06:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='semester',
            new_name='Semester',
        ),
        migrations.RemoveField(
            model_name='course',
            name='Is_Core',
        ),
    ]
