# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-14 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_interest'),
    ]

