# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-22 09:01
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('home', '0003_auto_20180221_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonProxy',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('home.person',),
        ),
        migrations.CreateModel(
            name='UserProxy',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
