# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-26 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_personproxy_userproxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='message',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
