# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-14 12:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_course_info'),
    ]

