# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-26 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_appointment_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='message',
            field=models.CharField(default='Pending Approval', max_length=1000),
        ),
    ]
