# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-26 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20180226_0822'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PersonProxy',
        ),
        migrations.DeleteModel(
            name='UserProxy',
        ),
        migrations.AlterField(
            model_name='person',
            name='is_doctor',
            field=models.BooleanField(default=True),
        ),
    ]
