# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-14 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_course_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='Credits',
        ),
        migrations.RemoveField(
            model_name='course',
            name='Semester',
        ),
        migrations.AddField(
            model_name='course',
            name='University',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
