# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-17 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20180214_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Image',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='Link',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
