# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-04 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20180226_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='is_doctor',
            field=models.BooleanField(default=False),
        ),
    ]
