# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-10 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20180304_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='is_doctor',
        ),
        migrations.AddField(
            model_name='person',
            name='type',
            field=models.IntegerField(default=0),
        ),
    ]
