# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-17 08:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20180217_0827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='Image',
        ),
    ]
