# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-10 17:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20180310_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receptionist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(default=None, max_length=100)),
                ('Email', models.CharField(default=None, max_length=100)),
                ('Phone', models.CharField(default=None, max_length=100)),
                ('gender', models.CharField(default=None, max_length=100)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.Person')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='Address',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='doctor',
            name='Email',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='doctor',
            name='Phone',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='doctor',
            name='gender',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='Address',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='Email',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='Phone',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
