# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-18 14:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='Date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
