# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-20 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_appointment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='Email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
