# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-20 13:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_appointment_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='Email',
        ),
    ]
