# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-20 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_remove_appointment_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('PD', 'Pending'), ('AP', 'Approved'), ('RJ', 'rejected')], default='PD', max_length=2),
        ),
    ]
