# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-21 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20180221_0600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='bio',
            field=models.TextField(blank=True, default=None, max_length=500),
        ),
    ]
